import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:signature/signature.dart';
import 'package:rap_app/services/database_service.dart';

class ContractScreen extends StatefulWidget {
  final Map<String, dynamic> job;
  const ContractScreen({super.key, required this.job});

  @override
  State<ContractScreen> createState() => _ContractScreenState();
}

class _ContractScreenState extends State<ContractScreen> {
  final SignatureController _userController = SignatureController(
    penStrokeWidth: 3,
    penColor: Colors.black,
    exportBackgroundColor: Colors.white,
  );
  
  final DatabaseService _db = DatabaseService();
  bool _isSaving = false;

  @override
  void dispose() {
    _userController.dispose();
    super.dispose();
  }

  Future<void> _signAndConfirm() async {
    if (_userController.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please provide your signature')));
      return;
    }

    setState(() => _isSaving = true);
    
    try {
      final bytes = await _userController.toPngBytes();
      if (bytes != null) {
        final userId = _db.currentUser?.uid ?? 'unknown';
        final signatureUrl = await _db.uploadData(
          'contracts/${widget.job['id']}/signature_$userId.png',
          bytes,
        );
        
        await _db.saveDigitalContract(widget.job['id'], {
          'agreement_text': _generateAgreement(),
          'signatureUrl': signatureUrl,
          'status': 'signed',
        });
      }

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Contract signed and active!')));
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  String _generateAgreement() {
    return """
SERVICE AGREEMENT
-----------------
Parties:
Customer: ${widget.job['customerName']}
Contractor: Assigned Partner

Project: ${widget.job['title']}
Location: ${widget.job['location']}
Amount: \$${widget.job['amount']}

By signing below, the customer and contractor agree to the scope of work defined in the AI estimate. The contractor warrants that they are licensed and insured (Verified by RAP). Payments will be handled according to milestone completion.

Generated by RAP Digital Contracts.
""";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        title: Text('Digital Agreement', style: GoogleFonts.outfit(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.transparent,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Theme.of(context).cardColor,
                borderRadius: BorderRadius.circular(24),
                border: Border.all(color: Theme.of(context).dividerColor.withValues(alpha: 0.1)),
              ),
              child: Text(
                _generateAgreement(),
                style: GoogleFonts.inter(height: 1.6, color: Theme.of(context).colorScheme.onSurface),
              ),
            ),
            const SizedBox(height: 32),
            Text('SIGNATURE', style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.bold, color: Theme.of(context).hintColor, letterSpacing: 1.5)),
            const SizedBox(height: 16),
            Container(
              height: 200,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: Theme.of(context).dividerColor),
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: Signature(
                  controller: _userController,
                  backgroundColor: Colors.white,
                ),
              ),
            ),
            const SizedBox(height: 12),
            TextButton.icon(
              onPressed: () => _userController.clear(),
              icon: const Icon(Icons.refresh, size: 18),
              label: const Text('Clear Signature'),
              style: TextButton.styleFrom(foregroundColor: Theme.of(context).colorScheme.error),
            ),
            const SizedBox(height: 48),
            SizedBox(
              width: double.infinity,
              height: 60,
              child: ElevatedButton(
                onPressed: _isSaving ? null : _signAndConfirm,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Theme.of(context).colorScheme.primary,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                ),
                child: _isSaving 
                  ? const CircularProgressIndicator(color: Colors.white)
                  : Text('Sign & Start Project', style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
